FROM golang:latest as builder

WORKDIR /app
COPY go.* /app/
RUN go mod download
COPY . /app/

# Edit this line to match your project structure
# change output binary name (server) and go main entry file
RUN CGO_ENABLED=0 go build  -o server  cmd/server/main.go


FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 3000

CMD ["./server"]

